import { clip, extractNumbers, normalizeForMatch, numberSet, words } from "@/lib/scripts/text";

/**
 * HOOK SCORE — transparent heuristic, 0–100, never a black box.
 *
 * Starts at 50 and adds/subtracts documented factors, each stored with its
 * delta and a reason a producer can check:
 *
 *   length        6–14 words is the Shorts sweet spot (first 2–3 seconds)
 *   specificity   concrete names / numbers beat generic phrasing (when the
 *                 story's facts are known, only details found in them count)
 *   curiosity     an open question or tension the video then answers
 *   clarity       one idea, few clauses, short words
 *   clickbait     false-promise phrases ("you won't believe", "shocking truth"),
 *                 ALL CAPS, excessive punctuation → penalties
 *   facts         when the story's facts are known, numbers (−15 each) and
 *                 names (−10 each, a lighter penalty: name detection is a
 *                 heuristic) must appear in them — a hook can't promise
 *                 invented facts
 *
 * The AI's own judgement is blended in by blendHookScore (hooks generated by
 * the Hook agent); manual hooks use the heuristic alone.
 */

export const HOOK_SCORING_VERSION = "hook-v1";
export const HOOK_BASE_SCORE = 50;

export type HookFactorName =
  | "length"
  | "specificity"
  | "curiosity_gap"
  | "clarity"
  | "clickbait"
  | "all_caps"
  | "punctuation"
  | "unsupported_number"
  | "unsupported_name"
  | "grounded";

export type HookFactor = { name: HookFactorName; delta: number; reason: string };

export type HookScore = {
  score: number;
  base: number;
  factors: HookFactor[];
  /** numbers in the hook that are not in any provided fact (only when facts were provided) */
  unsupportedNumbers: string[];
  version: string;
};

export type HookScoringContext = {
  /**
   * Claims of the story's facts. When provided (even empty), numbers and names
   * in the hook are checked against them; when undefined nothing is checkable.
   */
  facts?: readonly string[];
  /** other provided material names may come from (story title, logline, opportunity) */
  reference?: readonly string[];
};

export const HOOK_FACTOR_LABELS: Record<HookFactorName, string> = {
  length: "Length",
  specificity: "Specificity",
  curiosity_gap: "Curiosity gap",
  clarity: "Clarity",
  clickbait: "False clickbait",
  all_caps: "ALL CAPS",
  punctuation: "Punctuation",
  unsupported_number: "Number not in facts",
  unsupported_name: "Name not in facts",
  grounded: "Matches facts",
};

/** False-promise patterns: the video can't honestly deliver what they promise. */
const CLICKBAIT: { re: RegExp; delta: number; label: string }[] = [
  { re: /\byou (?:won['’]?t|will not|wont) believe\b/i, delta: -30, label: "“you won't believe”" },
  { re: /\bshocking truth\b/i, delta: -30, label: "“shocking truth”" },
  { re: /\b(?:will|gonna) (?:shock|blow) (?:you|your mind)\b/i, delta: -25, label: "“will shock you”" },
  { re: /\bwhat happen(?:s|ed) next (?:will|is)\b/i, delta: -20, label: "“what happens next will…”" },
  { re: /\bgone wrong\b/i, delta: -20, label: "“gone wrong”" },
  { re: /\b(?:doctors|experts|coaches|fans) hate\b/i, delta: -20, label: "“… hate this”" },
  { re: /\bmust[- ]see\b/i, delta: -12, label: "“must-see”" },
  { re: /\b(?:jaw[- ]dropping|mind[- ]blowing|insane|unbelievable)\b/i, delta: -10, label: "hype word" },
];

/** Capitalised words that start sentences or are too common to be names. */
const NOT_NAMES = new Set(
  (
    "a an the this that these those it its he she they we you i his her their our my your " +
    "why how what when who which where whose nobody no one everyone everybody someone somebody " +
    "in on at after before during since until from for with without by as to of into inside behind " +
    "and but or so then now today tonight yesterday tomorrow every all most some never ever still even only just " +
    "is was were are did does do can could would should will has have had not here there if " +
    "meet watch look remember imagine forget think guess wait stop " +
    "one two three four five six seven eight nine ten first last next new big"
  ).split(" "),
);

type NameToken = { token: string; sentenceStart: boolean };

/**
 * Likely proper names: capitalised words that are not common sentence starters.
 * All-caps tokens are left to the acronym / shouting checks.
 */
function capitalisedTokens(text: string): NameToken[] {
  const tokens = text.split(/\s+/);
  const out: NameToken[] = [];
  tokens.forEach((raw, i) => {
    const t = raw.replace(/^[^\p{L}]+|[^\p{L}'’.-]+$/gu, "").replace(/['’]s$/u, "").replace(/[.-]+$/u, "");
    if (t.length < 3 || !/^\p{Lu}/u.test(t) || t === t.toUpperCase()) return;
    if (NOT_NAMES.has(t.toLowerCase())) return;
    const sentenceStart = i === 0 || /[.!?:]$/.test(tokens[i - 1] ?? "");
    if (!out.some((o) => o.token === t)) out.push({ token: t, sentenceStart });
  });
  return out;
}

function isShouting(text: string): boolean {
  const w = words(text).filter((x) => /\p{L}/u.test(x));
  const capsWords = w.filter((x) => x.length >= 2 && x === x.toUpperCase() && x !== x.toLowerCase());
  if (capsWords.some((x) => x.length >= 5)) return true;
  return w.length >= 3 && capsWords.length / w.length >= 0.5;
}

function punctuationIssues(text: string): number {
  const runs = text.match(/[!?]{2,}|\.{3,}|…/g) ?? [];
  const bangs = (text.match(/!/g) ?? []).length;
  return runs.length + (bangs > 1 && runs.length === 0 ? 1 : 0);
}

const CURIOSITY_CUES =
  /\b(?:nobody|no one|the (?:real )?reason|secret|hidden|behind|until|turned out|the moment|here'?s why|this is why|instead|actually|didn'?t|never|but|yet|what (?:nobody|no one))\b/i;

export function scoreHook(text: string, ctx: HookScoringContext = {}): HookScore {
  const factors: HookFactor[] = [];
  const add = (name: HookFactorName, delta: number, reason: string) => factors.push({ name, delta, reason });
  const trimmed = text.trim();
  const n = words(trimmed).length;

  // length
  if (n < 4) add("length", -15, `${n} word${n === 1 ? "" : "s"}: too short to promise anything.`);
  else if (n <= 5) add("length", 5, `${n} words: short; 6–14 words is the Shorts sweet spot.`);
  else if (n <= 14) add("length", 15, `${n} words: fits the first 2–3 seconds of a Short.`);
  else if (n <= 18) add("length", -5, `${n} words: a little long for the opening seconds.`);
  else if (n <= 25) add("length", -10, `${n} words: too long; viewers decide in 2–3 seconds.`);
  else add("length", -20, `${n} words: far too long for a hook.`);

  // specificity
  const numbers = extractNumbers(trimmed);
  const checkable = ctx.facts !== undefined;
  const allowedNumbers = checkable ? numberSet(ctx.facts ?? []) : null;
  const haystack = checkable ? ` ${normalizeForMatch([...(ctx.facts ?? []), ...(ctx.reference ?? [])].join(" "))} ` : "";
  const inReference = (name: string) => haystack.includes(` ${normalizeForMatch(name)} `);
  const candidates = capitalisedTokens(trimmed);
  const shouting = isShouting(trimmed);
  // a capitalised first word is only a name if the story material says so ("Bologna…" yes, "Stunning…" no)
  const names = candidates.filter((c) => !c.sentenceStart || (checkable && inReference(c.token))).map((c) => c.token);
  // shouted words are not acronyms ("THIS IS" ≠ "PSG")
  const acronyms = shouting ? [] : words(trimmed).filter((w) => /^\p{Lu}{2,4}$/u.test(w));
  // when the facts are known, only details found in them make a hook specific (the rest is penalised below)
  const specificNumbers = allowedNumbers ? numbers.filter((x) => allowedNumbers.has(x)) : numbers;
  const specificNames = checkable ? [...names, ...acronyms].filter(inReference) : [...names, ...acronyms];
  const specific: string[] = [];
  if (specificNumbers.length) specific.push(`number ${specificNumbers.slice(0, 2).join(", ")}`);
  if (specificNames.length) specific.push(`name ${specificNames.slice(0, 2).join(", ")}`);
  if (specific.length === 2) add("specificity", 12, `Concrete details: ${specific.join(" and ")}.`);
  else if (specific.length === 1) add("specificity", 6, `Concrete detail: ${specific[0]}.`);
  else add("specificity", -5, checkable ? "Generic: no name or number from the facts to anchor it." : "Generic: no name or number to anchor it.");

  // curiosity gap
  let curiosity = 0;
  const reasons: string[] = [];
  if (/\?\s*$/.test(trimmed) || /^(?:why|how|what|who|which|when)\b/i.test(trimmed)) {
    curiosity += 8;
    reasons.push("asks a question the video answers");
  }
  if (CURIOSITY_CUES.test(trimmed)) {
    curiosity += 7;
    reasons.push("sets up tension or a twist");
  }
  if (curiosity > 0) add("curiosity_gap", Math.min(12, curiosity), `Open loop: ${reasons.join("; ")}.`);
  else add("curiosity_gap", -3, "No open question or tension: the whole story is given up front.");

  // clarity
  const clauses = (trimmed.match(/[,;:]|\s[—–-]\s/g) ?? []).length;
  const letters = words(trimmed).map((w) => w.length);
  const avgLen = letters.length ? letters.reduce((a, b) => a + b, 0) / letters.length : 0;
  if (clauses >= 3) add("clarity", -6, `${clauses} clauses: hard to take in at a glance.`);
  else if (avgLen > 7.5) add("clarity", -4, "Long words slow the first seconds down.");
  else if (n >= 4) add("clarity", 5, "One clear idea in plain words.");

  // false clickbait
  let clickbait = 0;
  const hits: string[] = [];
  for (const c of CLICKBAIT) {
    if (c.re.test(trimmed)) {
      clickbait += c.delta;
      hits.push(c.label);
    }
  }
  if (hits.length) add("clickbait", Math.max(-40, clickbait), `False-promise phrasing: ${hits.join(", ")}.`);
  if (shouting) add("all_caps", -15, "ALL CAPS reads as shouting and clickbait.");
  const punct = punctuationIssues(trimmed);
  if (punct > 0) add("punctuation", Math.max(-16, -8 * punct), "Excessive punctuation (!!, ?!, …) reads as clickbait.");

  // facts (only when checkable)
  const unsupportedNumbers: string[] = [];
  if (ctx.facts !== undefined && allowedNumbers) {
    for (const num of numbers) if (!allowedNumbers.has(num)) unsupportedNumbers.push(num);
    if (unsupportedNumbers.length) {
      add(
        "unsupported_number",
        Math.max(-30, -15 * unsupportedNumbers.length),
        `${unsupportedNumbers.map((x) => `“${x}”`).join(", ")} ${unsupportedNumbers.length === 1 ? "is" : "are"} not in the provided facts${ctx.facts.length ? "" : " (none recorded)"}.`,
      );
    }
    // sentence-initial words are never penalised: too often ordinary words
    const unknownNames = candidates.filter((c) => !c.sentenceStart && !inReference(c.token)).map((c) => c.token);
    if (unknownNames.length) {
      add(
        "unsupported_name",
        Math.max(-20, -10 * unknownNames.length),
        `${unknownNames.slice(0, 3).map((x) => `“${clip(x, 30)}”`).join(", ")} not found in the facts or story.`,
      );
    }
    if (!unsupportedNumbers.length && !unknownNames.length && (numbers.length || names.length)) {
      add("grounded", 5, "Every number and name matches the provided facts.");
    }
  }

  const raw = HOOK_BASE_SCORE + factors.reduce((sum, f) => sum + f.delta, 0);
  return {
    score: Math.max(0, Math.min(100, Math.round(raw))),
    base: HOOK_BASE_SCORE,
    factors,
    unsupportedNumbers,
    version: HOOK_SCORING_VERSION,
  };
}

/**
 * Final score of an AI-generated hook. The transparent heuristic carries most
 * of the weight so the model can't talk a clickbait hook back up; the model's
 * own 0–100 judgement adds what heuristics miss (relevance to the story, voice).
 */
export const HOOK_BLEND = { heuristic: 0.6, ai: 0.4 } as const;

export function blendHookScore(heuristic: number, ai: number | null | undefined): number {
  if (ai === null || ai === undefined || !Number.isFinite(ai)) return heuristic;
  const a = Math.max(0, Math.min(100, ai));
  return Math.max(0, Math.min(100, Math.round(HOOK_BLEND.heuristic * heuristic + HOOK_BLEND.ai * a)));
}
